### ISSUE TITLE
iOS Mobile onboarding 

### ISSUE THREAD

**Issue by alvinwklee** [calvinckho/restvo-app#31] opened 2020-04-07 01:31 UTC
- Carousel indicators are not visible within dark mode

- Screen is vertically scrollable when it shouldn't be

- No way for user to go back or exit from this page

![image](https://user-images.githubusercontent.com/41273385/78619327-eccfe680-7831-11ea-8f82-9ddaad95a2ee.png)

**Comment by calvinckho** [comment] 2020-04-07 04:32
Hi @xinluzhou Can you take a look at this? It is located in /src/app/pages/user/register. @alvinwklee I can't reproduce the vertical scrollability on my iPhone 7. Are you on iPhone X?

**Comment by alvinwklee** [comment] 2020-04-07 07:39
> Hi @xinluzhou Can you take a look at this? It is located in /src/app/pages/user/register. @alvinwklee I can't reproduce the vertical scrollability on my iPhone 7. Are you on iPhone X?

I'm using an iPhone XR. The vertical scroll seems to apply to all pages throughout the onboarding. Also, when switching between e-mail sign-up and mobile sign-up, it scrolls past the "Upload Profile Picture" screen briefly. There also seems to be a horizontal line on the bottom when scrolling down after switching between the two. 

![File from iOS](https://user-images.githubusercontent.com/41273385/78642773-19065a00-7868-11ea-8d93-a86e9fda9bf4.gif)

**Comment by xinluzhou** [comment] 2020-04-07 09:42
I am on Iphone X, I will take a look!

**Comment by calvinckho** [comment] 2020-05-07 04:48
@xinluzhou any update on this issue?

**Comment by xinluzhou** [comment] 2020-05-08 20:12
Sorry, I still cannot get my xcode work.

**Comment by calvinckho** [comment] 2020-05-18 17:37
@xinluzhou Can you get your Xcode to work now?

**Comment by calvinckho** [comment] 2020-06-09 06:24
@Ananya157 any update on this?

**Comment by calvinckho** [comment] 2020-07-09 22:18
@xinluzhou any chance you can get your Xcode to work?

**Comment by calvinckho** [comment] 2020-07-23 21:00
fixed in 1.8.16 (1)

**Closed by calvinckho** 2020-07-23 21:00 UTC
Labels: bug
