### ISSUE TITLE
Me Page Handoff

### ISSUE THREAD

**Issue by alvinwklee** [calvinckho/restvo-app#64] opened 2020-04-25 18:18 UTC
https://www.figma.com/file/qD4InkFEzspNx4OWGzijLV/Restvo-Me-Page?node-id=598%3A0

**Comment by calvinckho** [comment] 2020-04-27 22:04
@calixo888 Thanks Alvin. Calix will be in charge of implementing the styling and I will add the About Me card and wire up the the text box response logic.

**Comment by calvinckho** [comment] 2020-04-27 22:10
Duplicate of #17

**Closed by calvinckho** 2020-04-27 22:10 UTC
